# See the documentation for more information:
# https://packit.dev/docs/configuration/
---

specfile_path: resalloc-aws.spec
upstream_package_name: resalloc-aws
downstream_package_name: resalloc-aws
upstream_project_url: https://github.com/praiskup/resalloc-aws
upstream_tag_template: 'resalloc-aws-{version}'

actions:
  get-current-version:
    - bash -c "git describe --match resalloc-aws-[0-9]* --abbrev=0 HEAD | egrep -o [0-9]+\.[0-9]+"
  create-archive:
    - bash -c "tito build --tgz --test -o ."
    - bash -c "ls -1t *.tar.gz | head -n 1"

srpm_build_deps:
  - tito

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-all-x86_64
      - epel-all-x86_64

  - <<: *copr
    trigger: commit
    metadata:
      owner: "praiskup"
      project: "resalloc"
      branch: main
