# See the documentation for more information:
# https://packit.dev/docs/configuration/
---
jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    identifier: mock
    metadata:
      targets:
        - fedora-all-x86_64
        - epel-all-x86_64
    actions:
      create-archive:
        - bash -c "tito build --tgz --test -o ."
        - bash -c "ls -1t *.tar.gz | head -n 1"
      get-current-version:
        - bash -c "git describe --match resalloc-aws-[0-9]* --abbrev=0 HEAD | egrep -o [0-9]+\.[0-9]+"
    specfile_path: resalloc-aws.spec
    srpm_build_deps:
      - tito
    upstream_package_name: resalloc-aws
    downstream_package_name: resalloc-aws
    upstream_tag_template: 'resalloc-aws-{version}'

  - <<: *copr
    trigger: commit
    metadata:
      owner: "praiskup"
      project: "resalloc"
      branch: main
